from iso639 import languages

united_nations_style_languages = {'en', 'de', 'fr', 'es', 'pt', '中文', 'عربية'}

popular_languages_in_english = {
    'fijian', 'filipino', 'malagasy', 'samoan', 'tahitian', 'tongan',
    "abkhazian", "afar", "afrikaans", "akan", "albanian", "amharic","arabic", "aragonese", "armenian", "assamese","avaric","avestan","aymara","azerbaijani",
    "bambara","bashkir","basque","belarusian","bengali","bislama","bosnian","breton","bulgarian","burmese",
    "catalan","chamorro","chechen","chichewa","chinese","chuvash","cornish","corsican","cree","croatian","czech",
    "danish","divehi","dutch","dzongkha",
    "english","esperanto","estonian","ewe",
    "faroese","fijian","finnish","french","fulah",
    "galician","georgian","german","greek","guarani","gujarati",
    "haitian","hausa","hebrew","herero","hindi","hiri motu","hungarian",
    "indonesian","irish","igbo","inupiaq","ido","icelandic","italian","inuktitut",
    "japanese","javanese",
    "kalaallisut","greenlandic","kannada","kanuri","kashmiri","kazakh","central khmer","kikuyu","gikuyu","kinyarwanda","kirghiz","kyrgyz","komi","kongo","korean","kurdish","kuanyama",
    "latin","luxembourgish","ganda","limburgan","limburger","limburgish","lingala","lao","lithuanian","luba-katanga","latvian",
    "manx","macedonian","malagasy","malay","malayalam","maltese","maori","marathi","marshallese","mongolian",
    "nauru","navajo","navaho","north ndebele","nepali","ndonga","norwegian bokmål","norwegian nynorsk","norwegian",
    "sichuan yi","nuosu","south ndebele",
    "occitan","ojibwa","oromo","oriya","ossetian","ossetic",
    "punjabi","panjabi","pali","persian","polish","pashto","pushto","portuguese","quechua",
    "romansh","rundi","romanian","moldavian","moldovan","russian",
    "sanskrit","sardinian","sindhi","northern sami","samoan","sango","serbian","gaelic","scottish","shona","sinhala","sinhalese","slovak","slovenian","somali","southern sotho","spanish","castilian","sundanese","swahili","swati","swedish",
    "tamil","telugu","tajik","thai","tigrinya","tibetan","turkmen","tagalog","tswana","tonga","turkish","tsonga","tatar","twi","tahitian","uighur",
    "uyghur","ukrainian","urdu","uzbek",
    "venda","vietnamese","volapük","walloon","welsh","wolof","western frisian","xhosa",
    "yiddish","yoruba","zhuang","chuang","zulu",
}

popular_languages_in_russian = {
    'английский', 'арабский', 'африкаанс',
    'болгарский', 'боснийский (латиница)',
    'валлийский', 'венгерский', 'вьетнамский',
    'гаитянский креольский', 'голландский', 'греческий',
    'датский',
    'испанский', 'итальянский', 'иврит', 'индонезийский',
    'кантонский (традиционное письмо)', 'каталанский', 'керетарский отоми', 'китайский традиционный',
    'китайский упрощенный', 'клингонский', 'корейский', 'керетарский отоми',
    'латышский', 'литовский',
    'малайский', 'мальтийский',
    'немецкий', 'норвежский',
    'персидский', 'польский', 'португальский',
    'румынский',
    'сербский (кириллица)', 'сербский (латиница)', 'словацкий', 'словенский', 'суахили',
    'тайский', 'турецкий',
    'украинский', 'урду',
    'финский', 'французский',
    'хинди', 'хмонг дау', 'хорватский',
    'чешский',
    'шведский',
    'эстонский', 'юкатекский майя',
    'японский'
}

popular_languages_in_native = {
"аҧсшәа",
"afaraf",
"afrikaans",
"akan",
"shqip",
"አማርኛ",
"العربية",
"aragonés",
"հայերեն",
"অসমীয়া",
"авар мацӏ",
"avesta",
"aymar aru",
"azərbaycan dili",
"bamanankan",
"башҡорт теле",
"euskara",
"беларуская мова",
"বাংলা",
"bislama",
"bosanski jezik",
"brezhoneg",
"български език",
"ဗမာစာ",
"català",
"chamoru",
"нохчийн мотт",
"chicheŵa",
"中文 ",
"чӑваш чӗлхи",
"kernewek",
"corsu",
"lingua corsa",
"ᓀᐦᐃᔭᐍᐏᐣ",
"hrvatski jezik",
"čeština",
"dansk",
"ދިވެހި",
"nederlands",
"རྫོང་ཁ",
"english",
"esperanto",
"eesti",
"eʋegbe",
"føroyskt",
"vosa vakaviti",
"suomi",
"français",
"fulfulde",
"galego",
"ქართული",
"deutsch",
"ελληνικά",
"avañe'ẽ",
"ગુજરાતી",
"kreyòl ayisyen",
"(hausa) هَوُسَ",
"עברית",
"otjiherero",
"हिन्दी",
"हिंदी",
"hiri motu",
"magyar",
"interlingua",
"bahasa indonesia",
"gaeilge",
"asụsụ igbo",
"iñupiaq",
"ido",
"íslenska",
"italiano",
"ᐃᓄᒃᑎᑐᑦ",
"日本語 ",
"ꦧꦱꦗꦮ",
"basa jawa",
"kalaallisut",
"kalaallit oqaasii",
"ಕನ್ನಡ",
"kanuri",
"कश्मीरी",
"شميري‎",
"қазақ тілі",
"ខ្មែរ",
"ខេមរភាសា",
"ភាសាខ្មែរ",
"gĩkũyũ",
"ikinyarwanda",
"кыргызча",
"коми кыв",
"kikongo",
"한국어",
" کوردی‎",
"kuanyama",
"latine",
"lëtzebuergesch",
"luganda",
"limburgs",
"lingála",
"ພາສາລາວ",
"lietuvių kalba",
"kiluba",
"latviešu valoda",
"gaelg",
"gailck",
"македонски јазик",
"fiteny malagasy",
"بهاس ملايو‎",
"മലയാളം",
"malti",
"te reo māori",
"मराठी",
"kajin m̧ajeļ",
"монгол хэл",
"dorerin naoero",
"diné bizaad",
"isindebele",
"नेपाली",
"owambo",
"norsk bokmål",
"norsk nynorsk",
"norsk",
"ꆈꌠ꒿ nuosuhxop",
"isindebele",
"occitan",
"ᐊᓂᔑᓈᐯᒧᐎᓐ",
"afaan oromoo",
"ଓଡ଼ିଆ",
"ирон ӕвзаг",
"ਪੰਜਾਬੀ",
"پنجابی‎",
"पालि",
"पाळि",
"فارسی",
"polski",
"پښتو",
"português",
"runa simi",
"kichwa",
"rumantsch grischun",
"ikirundi",
"română, moldovenească",
"русский",
"संस्कृतम्",
"𑌸𑌂𑌸𑍍𑌕𑍃𑌤𑌮𑍍",
"sardu",
"सिन्धी",
" سنڌي، سندھی",
"davvisámegiella",
"gagana fa'a samoa",
"yângâ tî sängö",
"српски језик",
"gàidhlig",
"chishona",
"සිංහල",
"slovenčina",
"slovenščina",
"soomaaliga",
"sesotho",
"español",
"basa sunda",
"kiswahili",
"siswati",
"svenska",
"தமிழ்",
"తెలుగు",
"тоҷикӣ",
" toçikī",
" تاجیکی‎",
"ไทย",
"ትግርኛ",
"བོད་ཡིག",
"türkmen",
"түркмен",
"wikang tagalog",
"setswana",
"faka tonga",
"türkçe",
"xitsonga",
"татар теле",
"twi",
"reo tahiti",
"ئۇيغۇرچەuyghurche",
"українська",
"اردو",
"أۇزبېك‎",
"tshivenḓa",
"tiếng việt",
"volapük",
"walon",
"cymraeg",
"wollof",
"frysk",
"isixhosa",
"ייִדיש",
"yorùbá",
"saɯ cueŋƅ",
"isizulu"
}

def is_human_language(l):
    if l is None:
        return False
    l = l.lower()
    if l in united_nations_style_languages:
        return True
    if l in popular_languages_in_russian:
        return True
    if l in popular_languages_in_english:
        return True
    if l in popular_languages_in_native:
        return True
    if len(l) == 3:
        try:
            if languages.get(part3=l) is not None:
                return True
        except Exception as exp:
            pass
    return False
