bad_link	www.mvd.ru	www.yandex.ru
good_link	mvd.ru	мвд.рф
good_link	www.mvd.ru	mvd.ru
bad_link	www.mvd.ru	www.mvd.ru/print=1
good_link	bagaev.donland.ru	donland.ru
good_link	kraevoy.hbr.sudrf.ru	files.sudrf.ru
good_link	kremlin.ru	static.kremlin.ru
good_link	ksl.spb.sudrf.ru	files.sudrf.ru
good_link	mil.ru	recrut.mil.ru
good_link	mil.ru	stat.mil.ru
bad_link	minpromtorg.gov.ru	gossluzhba.gov.ru
bad_link	minpromtorg.gov.ru	pravo.gov.ru
bad_link	minvostokrazvitia.ru	data.gov.ru
bad_link	minvostokrazvitia.ru	gossluzhba.gov.ru
good_link	minvostokrazvitia.ru	minvr.ru
bad_link	minvostokrazvitia.ru	publication.pravo.gov.ru
good_link	minvr.ru	minvostokrazvitia.ru
good_link	oblsud.tula.sudrf.ru	files.sudrf.ru
bad_link	oblsud.tula.sudrf.ru	kremlin.ru
bad_link	oren-rshn.ru	fsvps.ru
bad_link	oren-rshn.ru	pravo.gov.ru
bad_link	rosminzdrav.ru	pravo.gov.ru
good_link	rosminzdrav.ru	static-0.rosminzdrav.ru
good_link	rosminzdrav.ru	static-1.rosminzdrav.ru
good_link	rosminzdrav.ru	static-2.rosminzdrav.ru
good_link	rosminzdrav.ru	static-3.rosminzdrav.ru
good_link	stat.mil.ru	mil.ru
good_link	stat.mil.ru	recrut.mil.ru
bad_link	voronovskoe.ru	trud.mos.ru
bad_link	https://minvr.ru/press-center/collegium/5197/	http://vk.com/share.php?url=https://minvr.ru:443/press-center/collegium/5197/
good_link	https://oren-rshn.ru:443	https://oren-rshn.ru
good_link	http://adm.ugorsk.ru/about/vacancies/information_about_income/?SECTION_ID=5244&ELEMENT_ID=79278	http://adm.ugorsk.ru/bitrix/redirect.php?event1=catalog_out&amp;event2=%2Fupload%2Fiblock%2Fb59%2Fb59f80e6eaf7348f74e713219c169a24.pdf&amp;event3=%D0%9F%D0%B5%D1%87%D0%B5%D0%BD%D0%B5%D0%B2%D0%B0+%D0%9D%D0%98.pdf&amp;goto=%2Fupload%2Fiblock%2Fb59%2Fb59f80e6eaf7348f74e713219c169a24.pdf
