# Generated by Django 2.1.3 on 2020-04-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='название')),
                ('alpha2', models.CharField(blank=True, default=None, max_length=2, null=True, verbose_name='alpha-2 ISO_3166-1')),
                ('alpha3', models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='alpha-3 ISO_3166-1')),
                ('code', models.CharField(blank=True, default=None, max_length=13, null=True, verbose_name='code ISO 3166-2')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=200)),
                ('web_domain', models.CharField(max_length=64)),
                ('file_path', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='office name')),
                ('name_ru', models.TextField(null=True, verbose_name='office name')),
                ('name_en', models.TextField(null=True, verbose_name='office name')),
            ],
        ),
        migrations.CreateModel(
            name='OwnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_ru', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.IntegerField(null=True)),
                ('share', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.Country')),
                ('owntype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.OwnType')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_ru', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_ru', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.TextField(verbose_name='person name')),
                ('person_name_ru', models.TextField(null=True, verbose_name='person name')),
                ('person_name_en', models.TextField(null=True, verbose_name='person name')),
                ('income_year', models.IntegerField(null=True)),
                ('department', models.TextField(null=True)),
                ('department_ru', models.TextField(null=True)),
                ('department_en', models.TextField(null=True)),
                ('position', models.TextField(null=True)),
                ('position_ru', models.TextField(null=True)),
                ('position_en', models.TextField(null=True)),
                ('document_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.DocumentFile', verbose_name='document file')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.Person', verbose_name='person id')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.RealEstateType')),
                ('name_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.RealEstateType')),
                ('name_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.RealEstateType')),
                ('relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.Relative')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarations.Section')),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='relative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.Relative'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarations.Section'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.RealEstateType'),
        ),
        migrations.AddField(
            model_name='income',
            name='relative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.Relative'),
        ),
        migrations.AddField(
            model_name='income',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarations.Section'),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarations.Office', verbose_name='office name'),
        ),
    ]
