# Generated by Django 3.0.5 on 2020-04-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='office name')),
                ('name_ru', models.TextField(null=True, verbose_name='office name')),
                ('name_en', models.TextField(null=True, verbose_name='office name')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.TextField(verbose_name='person name')),
                ('person_name_ru', models.TextField(null=True, verbose_name='person name')),
                ('person_name_en', models.TextField(null=True, verbose_name='person name')),
                ('income_year', models.IntegerField(null=True)),
                ('department', models.TextField(null=True)),
                ('department_ru', models.TextField(null=True)),
                ('department_en', models.TextField(null=True)),
                ('position', models.TextField(null=True)),
                ('position_ru', models.TextField(null=True)),
                ('position_en', models.TextField(null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.Person', verbose_name='person id')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative', models.CharField(max_length=1)),
                ('name', models.TextField()),
                ('name_ru', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarations.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SPJsonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=200)),
                ('web_domain', models.CharField(max_length=64)),
                ('file_path', models.CharField(max_length=128)),
                ('intersection_status', models.CharField(max_length=16)),
                ('declarator_documentfile_id', models.IntegerField(null=True)),
                ('declarator_document_id', models.IntegerField(null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarations.Office', verbose_name='office name')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='spjsonfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='declarations.SPJsonFile', verbose_name='smart parser json file'),
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(verbose_name='office name')),
                ('country', models.CharField(max_length=2)),
                ('relative', models.CharField(max_length=1)),
                ('owntype', models.CharField(max_length=1)),
                ('square', models.IntegerField(null=True)),
                ('share', models.FloatField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarations.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('relative', models.CharField(max_length=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarations.Section')),
            ],
        ),
    ]
