# Generated by Django 2.1.3 on 2020-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0002_main_constants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='share',
            field=models.FloatField(null=True),
        ),
    ]
