# Generated by Django 3.0.5 on 2020-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0002_main_constants'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='parent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='region_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='type_id',
            field=models.IntegerField(null=True),
        ),
    ]
