ALL_COUNTRIES = [
    {"ru": "Россия", "en": "Russia ", "alpha2": "RU", "alpha3": "RUS"},
    {"ru": "США", "en": "United States", "alpha2": "US", "alpha3": "USA"},
    {"ru": "Украина", "en": "Ukraine", "alpha2": "UA", "alpha3": "UKR"},
    {"ru": "Черногория", "en": "Montenegro", "alpha2": "ME", "alpha3": "MNE"},
    {"ru": "Грузия", "en": "Georgia", "alpha2": "GE", "alpha3": "GEO"},
    {"ru": "Испания", "en": "Spain", "alpha2": "ES", "alpha3": "ESP"},
    {"ru": "ОАЭ", "en": "United Arab Emirates", "alpha2": "AE", "alpha3": "ARE"},
    {"ru": "Великобритания", "en": "United Kingdom", "alpha2": "GB", "alpha3": "GBR"},
    {"ru": "Греция", "en": "Greece", "alpha2": "GR", "alpha3": "GRC"},
    {"ru": "Болгария", "en": "Bulgaria", "alpha2": "BG", "alpha3": "BGR"},
    {"ru": "Франция", "en": "France", "alpha2": "FR", "alpha3": "FRA"},
    {"ru": "Латвия", "en": "Latvia", "alpha2": "LV", "alpha3": "LVA"},
    {"ru": "Германия", "en": "Germany", "alpha2": "DE", "alpha3": "DEU"},
    {"ru": "Таджикистан", "en": "Tajikistan", "alpha2": "TJ", "alpha3": "TJK"},
    {"ru": "Австрия", "en": "Austria", "alpha2": "AT", "alpha3": "AUT"},
    {"ru": "Демократическая Республика Конго", "en": "Democratic Republic of the Congo", "alpha2": "CD", "alpha3": "COD"},
    {"ru": "Италия", "en": "Italy", "alpha2": "IT", "alpha3": "ITA"},
    {"ru": "Финляндия", "en": "Finland", "alpha2": "FI", "alpha3": "FIN"},
    {"ru": "Швейцария", "en": "Switzerland", "alpha2": "CH", "alpha3": "CHE"},
    {"ru": "Кипр", "en": "Cyprus", "alpha2": "CY", "alpha3": "CYP"},
    {"ru": "Монако", "en": "Monaco", "alpha2": "MC", "alpha3": "MCO"},
    {"ru": "Таиланд", "en": "Thailand", "alpha2": "TH", "alpha3": "THA"},
    {"ru": "Беларусь", "en": "Belarus", "alpha2": "BY", "alpha3": "BLR"},
    {"ru": "Израиль", "en": "Israel", "alpha2": "IL", "alpha3": "ISR"},
    {"ru": "Эстония", "en": "Estonia", "alpha2": "EE", "alpha3": "EST"},
    {"ru": "Абхазия", "en": "Abkhazia", "alpha2": "\\N", "alpha3": "\\N"},
    {"ru": "Мексика", "en": "Mexico", "alpha2": "MX", "alpha3": "MEX"},
    {"ru": "Литва", "en": "Lithuania", "alpha2": "LT", "alpha3": "LTU"},
    {"ru": "Чехия", "en": "Czech Republic", "alpha2": "CZ", "alpha3": "CZE"},
    {"ru": "Португалия", "en": "Portugal", "alpha2": "PT", "alpha3": "PRT"},
    {"ru": "Казахстан", "en": "Kazakhstan", "alpha2": "KZ", "alpha3": "KAZ"},
    {"ru": "Прочее", "en": "Other", "alpha2": "\\N", "alpha3": "\\N"},
    {"ru": "Венгрия", "en": "Hungary", "alpha2": "HU", "alpha3": "HUN"},
    {"ru": "Крым", "en": "Crimea", "alpha2": "\\N", "alpha3": "\\N"},
    {"ru": "Австралия", "en": "Australia", "alpha2": "AU", "alpha3": "AUS"},
    {"ru": "Турция", "en": "Turkey", "alpha2": "TR", "alpha3": "TUR"},
    {"ru": "Узбекистан", "en": "Uzbekistan", "alpha2": "UZ", "alpha3": "UZB"},
    {"ru": "Китай", "en": "China", "alpha2": "CN", "alpha3": "CHN"},
    {"ru": "Армения", "en": "Armenia", "alpha2": "AM", "alpha3": "ARM"},
    {"ru": "Бельгия", "en": "Belgium", "alpha2": "BE", "alpha3": "BEL"},
    {"ru": "Швеция", "en": "Sweden", "alpha2": "SE", "alpha3": "SWE"},
    {"ru": "Египет", "en": "Egypt, Arab Rep.", "alpha2": "EG", "alpha3": "EGY"},
    {"ru": "Канада", "en": "Canada", "alpha2": "CA", "alpha3": "CAN"},
    {"ru": "Азербайджан", "en": "Azerbaijan", "alpha2": "AZ", "alpha3": "AZE"},
    {"ru": "Кыргызстан", "en": "Kyrgyzstan", "alpha2": "KG", "alpha3": "KGZ"},
    {"ru": "Молдова", "en": "Moldova", "alpha2": "MD", "alpha3": "MDA"},
    {"ru": "Южная Осетия", "en": "South Oeetia", "alpha2": "\\N", "alpha3": "\\N"},
    {"ru": "Южно-Африканская Республика", "en": "South Africa", "alpha2": "ZA", "alpha3": "ZAF"},
    {"ru": "Индия", "en": "India", "alpha2": "IN", "alpha3": "IND"},
    {"ru": "Не указана", "en": "Not specified ", "alpha2": "\\N", "alpha3": "\\N"},
    {"ru": "Аландские острова", "en": "Aland", "alpha2": "AX", "alpha3": "ALA"},
    {"ru": "Албания", "en": "Albania", "alpha2": "AL", "alpha3": "ALB"},
    {"ru": "Алжир", "en": "Algeria", "alpha2": "DZ", "alpha3": "DZA"},
    {"ru": "Виргинские Острова (США)", "en": "the United States Virgin Islands", "alpha2": "VI", "alpha3": "VIR"},
    {"ru": "Американское Самоа", "en": "American Samoa", "alpha2": "AS", "alpha3": "ASM"},
    {"ru": "Ангилья", "en": "Anguilla", "alpha2": "AI", "alpha3": "AIA"},
    {"ru": "Ангола", "en": "Angola", "alpha2": "AO", "alpha3": "AGO"},
    {"ru": "Андорра", "en": "Andorra", "alpha2": "AD", "alpha3": "AND"},
    {"ru": "Антарктида", "en": "Antarctica", "alpha2": "AQ", "alpha3": "ATA"},
    {"ru": "Антигуа и Барбуда", "en": "Antigua and Barbuda", "alpha2": "AG", "alpha3": "ATG"},
    {"ru": "Аргентина", "en": "Argentina", "alpha2": "AR", "alpha3": "ARG"},
    {"ru": "Аруба", "en": "Aruba", "alpha2": "AW", "alpha3": "ABW"},
    {"ru": "Афганистан", "en": "Afghanistan", "alpha2": "AF", "alpha3": "AFG"},
    {"ru": "Багамские Острова", "en": "Afghanistan", "alpha2": "BS", "alpha3": "BHS"},
    {"ru": "Бангладеш", "en": "Bangladesh", "alpha2": "BD", "alpha3": "BGD"},
    {"ru": "Барбадос", "en": "Barbados", "alpha2": "BB", "alpha3": "BRB"},
    {"ru": "Бахрейн", "en": "Bahrain", "alpha2": "BH", "alpha3": "BHR"},
    {"ru": "Белиз", "en": "Belize", "alpha2": "BZ", "alpha3": "BLZ"},
    {"ru": "Бенин", "en": "Benin", "alpha2": "BJ", "alpha3": "BEN"},
    {"ru": "Бермуды", "en": "Bermuda", "alpha2": "BM", "alpha3": "BMU"},
    {"ru": "Боливия", "en": "Bolivia", "alpha2": "BO", "alpha3": "BOL"},
    {"ru": "Бонэйр, Синт-Эстатиус и Саба", "en": "Caribbean Netherlands", "alpha2": "BQ", "alpha3": "BES"},
    {"ru": "Босния и Герцеговина", "en": "Bosnia and Herzegovina", "alpha2": "BA", "alpha3": "BIH"},
    {"ru": "Ботсвана", "en": "Botswana", "alpha2": "BW", "alpha3": "BWA"},
    {"ru": "Бразилия", "en": "Brazil", "alpha2": "BR", "alpha3": "BRA"},
    {"ru": "Британская территория в Индийском океане", "en": "British Indian Ocean Territory", "alpha2": "IO", "alpha3": "IOT"},
    {"ru": "Виргинские Острова (Великобритания)", "en": "the British Virgin Islands", "alpha2": "VG", "alpha3": "VGB"},
    {"ru": "Бруней", "en": "Brunei", "alpha2": "BN", "alpha3": "BRN"},
    {"ru": "Буркина-Фасо", "en": "Burkina Faso", "alpha2": "BF", "alpha3": "BFA"},
    {"ru": "Бурунди", "en": "Burundi", "alpha2": "BI", "alpha3": "BDI"},
    {"ru": "Бутан", "en": "Bhutan", "alpha2": "BT", "alpha3": "BTN"},
    {"ru": "Вануату", "en": "Vanuatu", "alpha2": "VU", "alpha3": "VUT"},
    {"ru": "Ватикан", "en": "the Vatican City", "alpha2": "VA", "alpha3": "VAT"},
    {"ru": "Венесуэла", "en": "Venezuela", "alpha2": "VE", "alpha3": "VEN"},
    {"ru": "Внешние малые острова США", "en": "United States Minor Outlying Islands", "alpha2": "UM", "alpha3": "UMI"},
    {"ru": "Восточный Тимор", "en": "East Timor", "alpha2": "TL", "alpha3": "TLS"},
    {"ru": "Вьетнам", "en": "Vietnam", "alpha2": "VN", "alpha3": "VNM"},
    {"ru": "Габон", "en": "Gabon", "alpha2": "GA", "alpha3": "GAB"},
    {"ru": "Гаити", "en": "Haiti", "alpha2": "HT", "alpha3": "HTI"},
    {"ru": "Гайана", "en": "Guyana", "alpha2": "GY", "alpha3": "GUY"},
    {"ru": "Гамбия", "en": "The Gambia", "alpha2": "GM", "alpha3": "GMB"},
    {"ru": "Гана", "en": "Ghana", "alpha2": "GH", "alpha3": "GHA"},
    {"ru": "Гваделупа", "en": "Guadeloupe", "alpha2": "GP", "alpha3": "GLP"},
    {"ru": "Гватемала", "en": "Guatemala", "alpha2": "GT", "alpha3": "GTM"},
    {"ru": "Гвиана", "en": "Guyana", "alpha2": "GF", "alpha3": "GUF"},
    {"ru": "Гвинея", "en": "Guinea", "alpha2": "GN", "alpha3": "GIN"},
    {"ru": "Гвинея-Бисау", "en": "Guinea-Bissau", "alpha2": "GW", "alpha3": "GNB"},
    {"ru": "Гернси", "en": "Guernsey", "alpha2": "GG", "alpha3": "GGY"},
    {"ru": "Гибралтар", "en": "Gibraltar", "alpha2": "GI", "alpha3": "GIB"},
    {"ru": "Гондурас", "en": "Honduras", "alpha2": "HN", "alpha3": "HND"},
    {"ru": "Гонконг", "en": "Hong Kong", "alpha2": "HK", "alpha3": "HKG"},
    {"ru": "Гренада", "en": "Grenada", "alpha2": "GD", "alpha3": "GRD"},
    {"ru": "Гренландия", "en": "Greenland", "alpha2": "GL", "alpha3": "GRL"},
    {"ru": "Гуам", "en": "Guam", "alpha2": "GU", "alpha3": "GUM"},
    {"ru": "Дания", "en": "Denmark", "alpha2": "DK", "alpha3": "DNK"},
    {"ru": "Джерси", "en": "Jersey", "alpha2": "JE", "alpha3": "JEY"},
    {"ru": "Джибути", "en": "Djibouti", "alpha2": "DJ", "alpha3": "DJI"},
    {"ru": "Доминика", "en": "Dominica", "alpha2": "DM", "alpha3": "DMA"},
    {"ru": "Доминиканская Республика", "en": "Dominican Republic", "alpha2": "DO", "alpha3": "DOM"},
    {"ru": "Европейский союз", "en": "European Union", "alpha2": "EU", "alpha3": "\\N"},
    {"ru": "Замбия", "en": "Zambia", "alpha2": "ZM", "alpha3": "ZMB"},
    {"ru": "САДР", "en": "the Sahrawi Arab Democratic Republic", "alpha2": "EH", "alpha3": "ESH"},
    {"ru": "Зимбабве", "en": "Zimbabwe", "alpha2": "ZW", "alpha3": "ZWE"},
    {"ru": "Индонезия", "en": "Indonesia", "alpha2": "ID", "alpha3": "IDN"},
    {"ru": "Иордания", "en": "Jordan", "alpha2": "JO", "alpha3": "JOR"},
    {"ru": "Ирак", "en": "Iraq", "alpha2": "IQ", "alpha3": "IRQ"},
    {"ru": "Иран", "en": "Iran", "alpha2": "IR", "alpha3": "IRN"},
    {"ru": "Ирландия", "en": "Ireland", "alpha2": "IE", "alpha3": "IRL"},
    {"ru": "Исландия", "en": "Iceland", "alpha2": "IS", "alpha3": "ISL"},
    {"ru": "Йемен", "en": "Yemen", "alpha2": "YE", "alpha3": "YEM"},
    {"ru": "Кабо-Верде", "en": "Cape Verde", "alpha2": "CV", "alpha3": "CPV"},
    {"ru": "Острова Кайман", "en": "the Cayman Islands", "alpha2": "KY", "alpha3": "CYM"},
    {"ru": "Камбоджа", "en": "Cambodia", "alpha2": "KH", "alpha3": "KHM"},
    {"ru": "Камерун", "en": "Cameroon", "alpha2": "CM", "alpha3": "CMR"},
    {"ru": "Катар", "en": "Qatar", "alpha2": "QA", "alpha3": "QAT"},
    {"ru": "Кения", "en": "Kenya", "alpha2": "KE", "alpha3": "KEN"},
    {"ru": "Кирибати", "en": "Kiribati", "alpha2": "KI", "alpha3": "KIR"},
    {"ru": "Китайская Республика", "en": "the Republic of China", "alpha2": "TW", "alpha3": "TWN"},
    {"ru": "КНДР (Корейская Народно-Демократическая Республика)", "en": "North Korea", "alpha2": "KP", "alpha3": "PRK"},
    {"ru": "Кокосовые острова", "en": "the Cocos (Keeling) Islands", "alpha2": "CC", "alpha3": "CCK"},
    {"ru": "Колумбия", "en": "Colombia", "alpha2": "CO", "alpha3": "COL"},
    {"ru": "Коморы", "en": "the Comoros", "alpha2": "KM", "alpha3": "COM"},
    {"ru": "Коста-Рика", "en": "Costa Rica", "alpha2": "CR", "alpha3": "CRI"},
    {"ru": "Кот-д’Ивуар", "en": "Côte d'Ivoire", "alpha2": "CI", "alpha3": "CIV"},
    {"ru": "Куба", "en": "Cuba", "alpha2": "CU", "alpha3": "CUB"},
    {"ru": "Кувейт", "en": "Kuwait", "alpha2": "KW", "alpha3": "KWT"},
    {"ru": "Кюрасао", "en": "Curaçao", "alpha2": "CW", "alpha3": "CUW"},
    {"ru": "Лаос", "en": "Laos", "alpha2": "LA", "alpha3": "LAO"},
    {"ru": "Лесото", "en": "Lesotho", "alpha2": "LS", "alpha3": "LSO"},
    {"ru": "Либерия", "en": "Liberia", "alpha2": "LR", "alpha3": "LBR"},
    {"ru": "Ливан", "en": "Lebanon", "alpha2": "LB", "alpha3": "LBN"},
    {"ru": "Ливия", "en": "Libya", "alpha2": "LY", "alpha3": "LBY"},
    {"ru": "Лихтенштейн", "en": "Liechtenstein", "alpha2": "LI", "alpha3": "LIE"},
    {"ru": "Люксембург", "en": "Luxembourg", "alpha2": "LU", "alpha3": "LUX"},
    {"ru": "Маврикий", "en": "Mauritius", "alpha2": "MU", "alpha3": "MUS"},
    {"ru": "Мавритания", "en": "Mauritania", "alpha2": "MR", "alpha3": "MRT"},
    {"ru": "Мадагаскар", "en": "Madagascar", "alpha2": "MG", "alpha3": "MDG"},
    {"ru": "Майотта", "en": "Mayotte", "alpha2": "YT", "alpha3": "MYT"},
    {"ru": "Макао", "en": "Macau", "alpha2": "MO", "alpha3": "MAC"},
    {"ru": "Северная Македония", "en": "North Macedonia", "alpha2": "MK", "alpha3": "MKD"},
    {"ru": "Малави", "en": "Malawi", "alpha2": "MW", "alpha3": "MWI"},
    {"ru": "Малайзия", "en": "Malaysia", "alpha2": "MY", "alpha3": "MYS"},
    {"ru": "Мали", "en": "Mali", "alpha2": "ML", "alpha3": "MLI"},
    {"ru": "Мальдивы", "en": "Maldives", "alpha2": "MV", "alpha3": "MDV"},
    {"ru": "Мальта", "en": "Malta", "alpha2": "MT", "alpha3": "MLT"},
    {"ru": "Марокко", "en": "Morocco", "alpha2": "MA", "alpha3": "MAR"},
    {"ru": "Мартиника", "en": "Martinique", "alpha2": "MQ", "alpha3": "MTQ"},
    {"ru": "Маршалловы Острова", "en": "the Marshall Islands", "alpha2": "MH", "alpha3": "MHL"},
    {"ru": "Микронезия", "en": "the Federated States of Micronesia", "alpha2": "FM", "alpha3": "FSM"},
    {"ru": "Мозамбик", "en": "Mozambique", "alpha2": "MZ", "alpha3": "MOZ"},
    {"ru": "Монголия", "en": "Mongolia", "alpha2": "MN", "alpha3": "MNG"},
    {"ru": "Монтсеррат", "en": "Montserrat", "alpha2": "MS", "alpha3": "MSR"},
    {"ru": "Мьянма", "en": "Myanmar", "alpha2": "MM", "alpha3": "MMR"},
    {"ru": "Намибия", "en": "Namibia", "alpha2": "\\N", "alpha3": "NAM"},
    {"ru": "Науру", "en": "Nauru", "alpha2": "NR", "alpha3": "NRU"},
    {"ru": "Непал", "en": "Nepal", "alpha2": "NP", "alpha3": "NPL"},
    {"ru": "Нигер", "en": "Niger", "alpha2": "NE", "alpha3": "NER"},
    {"ru": "Нигерия", "en": "Nigeria", "alpha2": "NG", "alpha3": "NGA"},
    {"ru": "Нидерланды", "en": "the Netherlands", "alpha2": "NL", "alpha3": "NLD"},
    {"ru": "Никарагуа", "en": "Nicaragua", "alpha2": "NI", "alpha3": "NIC"},
    {"ru": "Ниуэ", "en": "Niue", "alpha2": "NU", "alpha3": "NIU"},
    {"ru": "Новая Зеландия", "en": "New Zealand", "alpha2": "NZ", "alpha3": "NZL"},
    {"ru": "Новая Каледония", "en": "New Caledonia", "alpha2": "NC", "alpha3": "NCL"},
    {"ru": "Норвегия", "en": "Norway", "alpha2": "NO", "alpha3": "NOR"},
    {"ru": "Оман", "en": "Oman", "alpha2": "OM", "alpha3": "OMN"},
    {"ru": "Остров Буве", "en": "Bouvet Island", "alpha2": "BV", "alpha3": "BVT"},
    {"ru": "Остров Мэн", "en": "the Isle of Man", "alpha2": "IM", "alpha3": "IMN"},
    {"ru": "Острова Кука", "en": "the Cook Islands", "alpha2": "CK", "alpha3": "COK"},
    {"ru": "Остров Норфолк", "en": "Norfolk Island", "alpha2": "NF", "alpha3": "NFK"},
    {"ru": "Остров Рождества", "en": "Christmas Island", "alpha2": "CX", "alpha3": "CXR"},
    {"ru": "Острова Питкэрн", "en": "the Pitcairn Islands", "alpha2": "PN", "alpha3": "PCN"},
    {"ru": "Острова Святой Елены, Вознесения и Тристан-да-Кунья", "en": "Saint Helena, Ascension and Tristan da Cunha", "alpha2": "SH", "alpha3": "SHN"},
    {"ru": "Пакистан", "en": "Pakistan", "alpha2": "PK", "alpha3": "PAK"},
    {"ru": "Палау", "en": "Palau", "alpha2": "PW", "alpha3": "PLW"},
    {"ru": "Государство Палестина", "en": "Palestine", "alpha2": "PS", "alpha3": "PSE"},
    {"ru": "Панама", "en": "Panama", "alpha2": "PA", "alpha3": "PAN"},
    {"ru": "Папуа — Новая Гвинея", "en": "Papua New Guinea", "alpha2": "PG", "alpha3": "PNG"},
    {"ru": "Парагвай", "en": "Paraguay", "alpha2": "PY", "alpha3": "PRY"},
    {"ru": "Перу", "en": "Peru", "alpha2": "PE", "alpha3": "PER"},
    {"ru": "Польша", "en": "Poland", "alpha2": "PL", "alpha3": "POL"},
    {"ru": "Пуэрто-Рико", "en": "Puerto Rico", "alpha2": "PR", "alpha3": "PRI"},
    {"ru": "Республика Конго", "en": "Congo, Rep.", "alpha2": "CG", "alpha3": "COG"},
    {"ru": "Республика Корея", "en": "South Korea", "alpha2": "KR", "alpha3": "KOR"},
    {"ru": "Реюньон", "en": "Réunion", "alpha2": "RE", "alpha3": "REU"},
    {"ru": "Руанда", "en": "Rwanda", "alpha2": "RW", "alpha3": "RWA"},
    {"ru": "Румыния", "en": "Romania", "alpha2": "RO", "alpha3": "ROU"},
    {"ru": "Сальвадор", "en": "El Salvador", "alpha2": "SV", "alpha3": "SLV"},
    {"ru": "Самоа", "en": "Samoa", "alpha2": "WS", "alpha3": "WSM"},
    {"ru": "Сан-Марино", "en": "San Marino", "alpha2": "SM", "alpha3": "SMR"},
    {"ru": "Сан-Томе и Принсипи", "en": "Sao Tome and Principe", "alpha2": "ST", "alpha3": "STP"},
    {"ru": "Саудовская Аравия", "en": "Saudi Arabia", "alpha2": "SA", "alpha3": "SAU"},
    {"ru": "Эсватини", "en": "Eswatini", "alpha2": "SZ", "alpha3": "SWZ"},
    {"ru": "Северные Марианские Острова", "en": "the Northern Mariana Islands", "alpha2": "MP", "alpha3": "MNP"},
    {"ru": "Сейшельские Острова", "en": "Seychelles", "alpha2": "SC", "alpha3": "SYC"},
    {"ru": "Сен-Бартелеми (Карибы)", "en": "Saint Barthelemy", "alpha2": "BL", "alpha3": "BLM"},
    {"ru": "Сен-Мартен", "en": "Saint martin", "alpha2": "MF", "alpha3": "MAF"},
    {"ru": "Сен-Пьер и Микелон", "en": "Saint-Pierre and Miquelon", "alpha2": "PM", "alpha3": "SPM"},
    {"ru": "Сенегал", "en": "Senegal", "alpha2": "SN", "alpha3": "SEN"},
    {"ru": "Сент-Винсент и Гренадины", "en": "Saint Vincent and the Grenadines", "alpha2": "VC", "alpha3": "VCT"},
    {"ru": "Сент-Китс и Невис", "en": "Saint Kitts and Nevis", "alpha2": "KN", "alpha3": "KNA"},
    {"ru": "Сент-Люсия", "en": "Saint Lucia", "alpha2": "LC", "alpha3": "LCA"},
    {"ru": "Сербия", "en": "Serbia", "alpha2": "RS", "alpha3": "SRB"},
    {"ru": "Сингапур", "en": "Singapore", "alpha2": "SG", "alpha3": "SGP"},
    {"ru": "Синт-Мартен", "en": "Sint Maarten", "alpha2": "SX", "alpha3": "SXM"},
    {"ru": "Сирия", "en": "Syria", "alpha2": "SY", "alpha3": "SYR"},
    {"ru": "Словакия", "en": "Slovakia", "alpha2": "SK", "alpha3": "SVK"},
    {"ru": "Словения", "en": "Slovenia", "alpha2": "SI", "alpha3": "SVN"},
    {"ru": "Соломоновы Острова", "en": "the Solomon Islands", "alpha2": "SB", "alpha3": "SLB"},
    {"ru": "Сомали", "en": "Somalia", "alpha2": "SO", "alpha3": "SOM"},
    {"ru": "Судан", "en": "Sudan", "alpha2": "SD", "alpha3": "SDN"},
    {"ru": "Суринам", "en": "Suriname", "alpha2": "SR", "alpha3": "SUR"},
    {"ru": "Сьерра-Леоне", "en": "Sierra Leone", "alpha2": "SL", "alpha3": "SLE"},
    {"ru": "Танзания", "en": "Tanzania", "alpha2": "TZ", "alpha3": "TZA"},
    {"ru": "Теркс и Кайкос", "en": "the Turks and Caicos Islands", "alpha2": "TC", "alpha3": "TCA"},
    {"ru": "Того", "en": "Togo", "alpha2": "TG", "alpha3": "TGO"},
    {"ru": "Токелау", "en": "Tokelau", "alpha2": "TK", "alpha3": "TKL"},
    {"ru": "Тонга", "en": "Tonga", "alpha2": "TO", "alpha3": "TON"},
    {"ru": "Тринидад и Тобаго", "en": "Trinidad and Tobago", "alpha2": "TT", "alpha3": "TTO"},
    {"ru": "Тувалу", "en": "Tuvalu", "alpha2": "TV", "alpha3": "TUV"},
    {"ru": "Тунис", "en": "Tunisia", "alpha2": "TN", "alpha3": "TUN"},
    {"ru": "Туркмения", "en": "Turkmenistan", "alpha2": "TM", "alpha3": "TKM"},
    {"ru": "Уганда", "en": "Uganda", "alpha2": "UG", "alpha3": "UGA"},
    {"ru": "Уоллис и Футуна", "en": "Wallis and Futuna", "alpha2": "WF", "alpha3": "WLF"},
    {"ru": "Уругвай", "en": "Uruguay", "alpha2": "UY", "alpha3": "URY"},
    {"ru": "Фареры", "en": "the Faroe Islands", "alpha2": "FO", "alpha3": "FRO"},
    {"ru": "Фиджи", "en": "Fiji", "alpha2": "FJ", "alpha3": "FJI"},
    {"ru": "Филиппины", "en": "the Philippines", "alpha2": "PH", "alpha3": "PHL"},
    {"ru": "Фолклендские острова", "en": "the Falkland Islands", "alpha2": "FK", "alpha3": "FLK"},
    {"ru": "Французская Полинезия", "en": "French Polynesia", "alpha2": "PF", "alpha3": "PYF"},
    {"ru": "Французские Южные и Антарктические территории", "en": "French Southern and Antarctic Lands", "alpha2": "TF", "alpha3": "ATF"},
    {"ru": "Херд и Макдональд", "en": "Heard Island and McDonald Islands", "alpha2": "HM", "alpha3": "HMD"},
    {"ru": "Хорватия", "en": "Croatia", "alpha2": "HR", "alpha3": "HRV"},
    {"ru": "ЦАР", "en": "the Central African Republic", "alpha2": "CF", "alpha3": "CAF"},
    {"ru": "Чад", "en": "Chad", "alpha2": "TD", "alpha3": "TCD"},
    {"ru": "Чили", "en": "Chile", "alpha2": "CL", "alpha3": "CHL"},
    {"ru": "Шпицберген и Ян-Майен", "en": "Svalbard and Jan Mayen", "alpha2": "SJ", "alpha3": "SJM"},
    {"ru": "Шри-Ланка", "en": "Sri Lanka", "alpha2": "LK", "alpha3": "LKA"},
    {"ru": "Эквадор", "en": "Ecuador", "alpha2": "EC", "alpha3": "ECU"},
    {"ru": "Экваториальная Гвинея", "en": "Equatorial Guinea", "alpha2": "GQ", "alpha3": "GNQ"},
    {"ru": "Эритрея", "en": "Eritrea", "alpha2": "ER", "alpha3": "ERI"},
    {"ru": "Эфиопия", "en": "Ethiopia", "alpha2": "ET", "alpha3": "ETH"},
    {"ru": "Южная Георгия и Южные Сандвичевы Острова", "en": "South Georgia and the South Sandwich Islands", "alpha2": "GS", "alpha3": "SGS"},
    {"ru": "Южный Судан", "en": "South Sudan", "alpha2": "SS", "alpha3": "SSD"},
    {"ru": "Ямайка", "en": "Jamaica", "alpha2": "JM", "alpha3": "JAM"},
    {"ru": "Япония", "en": "Japan", "alpha2": "JP", "alpha3": "JPN"},

    {"ru": "Неизвестное государство", "en": "Unknown state", "alpha2": "??", "alpha3": "???"},
    {"ru": "Донецкая Народная Республика", "en": "Donetsk People's Republic", "alpha2": "?1", "alpha3": "??1"},
    {"ru": "Луганская Народная Республика", "en": "Luhansk People's Republic", "alpha2": "?2", "alpha3": "??2"},
]
CODE_TO_INFO = dict((x['alpha2'], x) for x in ALL_COUNTRIES)
RUSSIAN_TO_CODE = dict((x['ru'].lower(), x['alpha2']) for x in ALL_COUNTRIES)


def get_country_code(country_str):
    global RUSSIAN_TO_CODE
    if country_str is None:
        return "RU"
    country_str_lower = country_str.strip().lower()
    if country_str_lower == "" or \
       country_str_lower.find("росси") != -1 or \
       country_str_lower == "рф" or \
       country_str_lower == "-":
        return "RU"

    return RUSSIAN_TO_CODE.get(country_str_lower, "??")


def get_country_str(country_code, lang):
    i = CODE_TO_INFO[country_code]
    return i.get(lang, i.get("en"))
